on:
  push:
jobs:
  do_arm64:
    name: blar
    runs-on: [self-hosted, woa]
    steps:
    - run: |
        Write-Output "hello from $env:PROCESSOR_ARCHITECTURE"  # AMD64, since we launched from an x64 runner process
        $out = c:\python397_arm64\python -c "import platform; print(platform.processor())"
        Write-Output "hello from Python $out"  # yay, ARM64
      shell: pwsh  

